services:
  astream:
    build: .
    container_name: astream-addon
    ports:
      - "8000:8000"
    env_file:
      - .env
    # On monte le volume pour le développement (facultatif mais utile)
    volumes:
      - .:/app
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
